development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://rlroomnixrbtnn:j8_jae-vu2hXKdPMRFpLCG0Dvx@ec2-23-21-50-120.compute-1.amazonaws.com:5432/dfadu625piggb2